# Generated by Django 4.1.5 on 2023-01-24 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
                ('preco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Financiamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_vencimento', models.DateTimeField()),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculo')),
            ],
            options={
                'db_table': 'veiculo',
            },
        ),
    ]
