# Generated by Django 4.1.5 on 2023-04-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_car_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_user',
            old_name='loan_amount',
            new_name='loan_amount_2',
        ),
    ]
