# Generated by Django 4.1.5 on 2023-04-03 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_loan_amount_car_user_loan_amount_2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car_user',
            table='carro_2',
        ),
    ]
